/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * Do __not__ import components from this file as server side rendered components
 * may not hydrate due to missing Stencil runtime. Instead, import these components through the generated 'components.ts'
 * file that re-exports all components with the 'use client' directive.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';
import { MyComponent as MyComponentElement } from "stencil-library/components/my-component.js";
import { MyInput as MyInputElement } from "stencil-library/components/my-input.js";

export const serializeShadowRoot: SerializeShadowRootOptions = { default: "declarative-shadow-dom" };

export type MyComponentEvents = { onUpdateCount: EventName<CustomEvent<{ count: number }>> };

export const MyComponent: StencilReactComponent<MyComponentElement, MyComponentEvents> = /*@__PURE__*/ createComponent<MyComponentElement, MyComponentEvents>({
    tagName: 'my-component',
    properties: {
        first: 'first',
        middle: 'middle',
        last: 'last'
    },
    hydrateModule: import('stencil-library/hydrate'),
    serializeShadowRoot
});

export type MyInputEvents = NonNullable<unknown>;

export const MyInput: StencilReactComponent<MyInputElement, MyInputEvents> = /*@__PURE__*/ createComponent<MyInputElement, MyInputEvents>({
    tagName: 'my-input',
    properties: {
        placeholder: 'placeholder',
        errorMessage: 'error-message',
        label: 'label',
        inputValidator: 'input-validator'
    },
    hydrateModule: import('stencil-library/hydrate'),
    serializeShadowRoot
});
