/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    /**
     * Use `my-component` when you need to use My Component.
     * I expect all the custom text from this component's readme to be copied
     * to the docusaurus readme above ☝🏻.
     */
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface MyInput {
        "errorMessage": string;
        "inputValidator": (value: string) => Promise<string>;
        "label": string;
        "placeholder": string;
    }
}
export interface MyComponentCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMyComponentElement;
}
declare global {
    interface HTMLMyComponentElementEventMap {
        "updateCount": {count: number};
    }
    /**
     * Use `my-component` when you need to use My Component.
     * I expect all the custom text from this component's readme to be copied
     * to the docusaurus readme above ☝🏻.
     */
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
        addEventListener<K extends keyof HTMLMyComponentElementEventMap>(type: K, listener: (this: HTMLMyComponentElement, ev: MyComponentCustomEvent<HTMLMyComponentElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLMyComponentElementEventMap>(type: K, listener: (this: HTMLMyComponentElement, ev: MyComponentCustomEvent<HTMLMyComponentElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLMyInputElement extends Components.MyInput, HTMLStencilElement {
    }
    var HTMLMyInputElement: {
        prototype: HTMLMyInputElement;
        new (): HTMLMyInputElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "my-input": HTMLMyInputElement;
    }
}
declare namespace LocalJSX {
    /**
     * Use `my-component` when you need to use My Component.
     * I expect all the custom text from this component's readme to be copied
     * to the docusaurus readme above ☝🏻.
     */
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
        /**
          * A simple event to emit when the count is updated
          * @event updateCount
          * @description This event is emitted when the count is updated.
          * @type {Object} - The event detail
          * @property {number} count - The updated count value.
          * @example ```javascript const myComponent = document.querySelector('my-component'); myComponent.addEventListener('updateCount', (event) => {   console.log('Count updated:', event.detail.count); }); ```
         */
        "onUpdateCount"?: (event: MyComponentCustomEvent<{count: number}>) => void;
    }
    interface MyInput {
        "errorMessage"?: string;
        "inputValidator"?: (value: string) => Promise<string>;
        "label"?: string;
        "placeholder"?: string;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "my-input": MyInput;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * Use `my-component` when you need to use My Component.
             * I expect all the custom text from this component's readme to be copied
             * to the docusaurus readme above ☝🏻.
             */
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "my-input": LocalJSX.MyInput & JSXBase.HTMLAttributes<HTMLMyInputElement>;
        }
    }
}
